### ISSUE TITLE
where is the server.pfx file?

### ISSUE THREAD

**Issue by sliu1975** [endink/Thrifty#1]

**Comment by endink** [comment]
SERVER.PFX is a server X509 certificate for TSL, just like a regular HTTPS certificate, it can be generated by openssl command line tool,  to generate a certificate u can use follow command:

```
openssl req -new -newkey rsa:4096 -nodes -x509 -days 5480 -keyout "[CA_PRIVATE_KEY_FILE]" -out "ca.crt" -config "[openssl_config_file]" -subj "/C=US/ST=WD/L=Seattle/O=SOME/OU=DEV/CN=YOUDOMAIN.COM"

openssl pkcs12 -export -in "ca.crt" -inkey "[CA_PRIVATE_KEY_FILE]" -password pass:[CA_PASSWORD] -out "ca.pfx"

openssl genrsa -passout pass:[SERVER_PASSWORD] -out "server.key" 4096
openssl req -new -key "server.key" -passin pass:[SERVER_PASSWORD] -out "server.csr" -subj "/C=US/ST=WD/L=Seattle/O=SOME/OU=DEV/CN=localhost/CN=WWW.XXX.COM" -config "[openssl_config_file]"
 
openssl ca -in "server.csr" -out "server.crt" -cert "ca.crt" -keyfile "[CA_PRIVATE_KEY_FILE]" -passin pass:[SERVER_PASSWORD] -outdir "[SERVER_CRT_DIR]" -extensions "server exts" -config "[openssl_config_file]"


openssl pkcs12 -export -in "server.crt" -inkey "server.key" -passin pass:[SERVER_PASSWORD] -password pass:[SERVER_CRT_PSSWORD] -out "server.pfx"

```

Above is an example of using a self-signed certificate。

For self-signed certificate, to let your client trusts the CA chain, you need use ClientSslConfig method put the root ca into it (only need public key in the crt file)， If your server.pfx is from a trusted organization (like Symantec,Geo ...) , then the client does not need any configuration because the "CA" was installed by your operating system.
